config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  get 'my_events', to: 'events#my_events'
  resources :events
  resources :event_users
  resources :users

 

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  # this event is created by/belongs to a single user
  belongs_to :user

  # these are the validations that create safety and force people to fill out the create event form properly to my spcifications
  validates :event_name, presence: true, length: { minimum: 2, maximum: 25 }
  validates :description, presence: true, length: { minimum: 2, maximum: 200 }
  validates :date, presence: true, length: { minimum: 2, maximum: 15 }
  validates :time, presence: true, length: { minimum: 2, maximum: 15 }
  validates :address, presence: true, length: { minimum: 5, maximum: 60 }
  validates :location, length: { maximum: 100 }
  validates :difficulty, length: { maximum: 20 }

  # implements the geocoder gem using the address
  geocoded_by :address
  after_validation :geocode

  # relationship bewtween event and its users
  has_many :event_users
  has_many :users, through: :event_users
end

app/models/event_user.rb
class EventUser < ActiveRecord::Base
  # this is the join table that joins the users and their events also implements the counter
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :event_users
  has_many :events, through: :event_users # The ones I authored

  has_many :rsvps, through: :event_users, class_name: 'Event'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  alias_method :std_redirect_to, :redirect_to
  def redirect_to(*args)
    flash.keep
    std_redirect_to *args
  end
end

app/controllers/event_users_controller.rb
class EventUsersController < ApplicationController
  # this method creates the relationship on the event_user table that is used for the join button, once the person has joined an event they are redirected to their mt_event page
  def create
    current_user.event_users.create(params.require(:event_user).permit(:event_id))
    redirect_to my_events_path
  end

  # def counter
  #    @event_user.join_counter = @event_user.join_counter + 1

  # end
end

# helper_method :counter
# def counter
#      @event_user.join_counter = @event_user.join_counter + 1
#   end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # autheniticates user as loggedin for specific method usage
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create, :my_events]

  # method to list all events
  def index
    # creates instance variable for event index in descending order and pagination
    @events = Event.order(created_at: :desc).page(params[:page]).per(7)

    # possibly add .where to previous line to create filter for only recent events
    @event = EventUser.all
  end

  # allows you to display a newly created event as well as all the
  # events you are a part of using the user_id
  def show
    @event = Event.find_by_id(params[:id])
  end

  # creates a new event
  def new
    @event = Event.new
  end

  # creates a new event for a user with certain params, and attaches the event and user via event_user table
  def create
    @event = current_user.events.create(event_params)
    @user_events = current_user.events

    # if the event saves it shows the notification and redirects you to index page
    if @event.save
      flash[:notice] = 'Your Event was created'
      redirect_to event_path(@event)

    # if the event does not save you given a notification and directed back to create page
    else
      flash[:notice] = 'Your Event was not created, please retry!'
      redirect_to new_event_path
    end
  end

  # shows a page of only the current users events
  def my_events
    @events = current_user.events.page(params[:page]).per(7)
  end

  # allows the current user to edit their events
  def edit
    @event = Event.find(params[:id])
    # if @event.user_id != current_user.id
    #     flash[:error]= "You don't have permission to do that"
    #       redirect_to events_path
    # end
  end

  # updates the event after it has been edited and redirects back tot he index page
  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  # deletes items
  def destroy
    @event = Event.find_by_id(params[:id])
    @event.destroy
    redirect_to request.referer
  end

  # sets up the parameters taht are required to create an event as well as those permited to be filled
  private
  def event_params
    params.require(:event).permit(:event_name, :description, :date, :time, :address, :location, :difficulty)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_users_helper.rb
module EventUsersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
  <!-- this partial is used for interations through all the events for display purposes -->
  <div class="events">

  <div id="table">
  <p></p>
  
  <strong>Workout:</strong> <%=event.event_name %>- <%=event.description %>, <%=event.difficulty %><br>
  <strong>Date:</strong> <%=event.date %>
  <strong>Time:</strong> <%=event.time %><br>
  <strong>Address:</strong><%=event.address %>
  <strong>Location:</strong><%=event.location %>
  </div>

</div>

        
      
       
     

app/views/events/create.html.erb
CREATE PAGE<h1>New Work Out</h1>

<h2>Your New Workout</h2>
<p id="notice"><%= notice %></p> 

<p>
  <strong>Name:</strong>
  <%= @event.event_name %>
  <strong>Description:</strong>
  <%= @event.description %><br>
  <strong>Date:</strong>
  <%= @event.date %>
  <strong>Time:</strong>
  <%= @event.time %>
  <strong>Address:</strong>
  <%= @event.address %><br>
  <strong>Location:</strong>
  <%= @event.location%><br>
  <strong>Difficulty:</strong>
  <%= @event.difficulty %>
  <%= link_to 'Edit', edit_event_path(@event) %> 
  

  <%= link_to 'Back', events_path %><br>

  </p>
  <% if @event.user_id == current_user.id %>

  <% end %>



    <h2> All Your Workouts </h2>
    <% @user_events.each do |user_event| %>
        <%= render partial: "event", locals:{event: user_event.event} %>

         <%= link_to 'Edit', edit_event_path(event) %>
        <%= link_to 'Delete', event, method: :destroy, data: { confirm: 'Are you sure?' } %><br><br>
    <% end %>
       
     
   

</table>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<%= form_for(@event) do |f| %>
  

  <div class="field">
    <%= f.label :Workout %><br>
    <%= f.text_field :event_name %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :description %>
  </div>
      <%= f.label :Date %>
    <%= f.text_field :date %>
        <%= f.label :Time %>
    <%= f.text_field :time %>
        <%= f.label :Address %>
    <%= f.text_field :address %><br>
        <%= f.label :Location %>
    <%= f.text_field :location %>
        <%= f.label :Difficulty %>
    <%= f.text_field :difficulty %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<!-- <div class="heading">
<h1 id="banner">FIT..Buddy! </h1>
<h5 id="tag_line">Find people to workout with, you decide what, when, and where!</h5>
</div> -->

<div class="banner">
<h2 id="header">FIT..Buddy! </h2>
<h5 id="tag_line">Find people to workout with. You decide what, when, and where!</h5>
</div>

<hr class = "front_page">
<div class="splash">Welcome to Fit..Buddy. This website is designed for busy workout enthusiasts. Once you sign in you can create and join workouts with other people on your own schedule.</div>

    <div class="wrapper">
    <!-- link to new event page -->
        <div class="event_buttons">
        <div class= "center"></div>
        <div id="new_event_button"><%= link_to("Add Workout", new_event_path) %></div>
        <div></div>

      <!-- link to all the current users workouts -->
        <div id="my_event_button"><%= link_to("My Workouts", my_events_path) %></div><div></div>
    </div>

  <!-- creates pagination for each page after 7 items -->
<%= paginate @events.order(created_at: :desc) %>
<h3 id="workouts"><strong>Workouts</strong></h3>

<!-- check to see if there is a current user/signed in user -->
<% if current_user %>

<!-- if there is a current user it starts each iteration for listing the index of events from the DB -->
  <% @events.each do |event| %>
 <!--  renders the partial for the event index -->
    <%= render partial: "event", locals:{event: event} %>

    <p></p>
    <!-- checks to see if the current user_is and the event being listed have a common id from the event_user table if this is true it will do the iteration -->
      <% if current_user && event.event_users.where(user_id:current_user.id).first %>
      <h5 id="rsvp">People RSVP'D for this workout:
     <%= event.users.length %></h5> 
      <!-- replaces the "join button" to show the user that they ahve already joined this event -->
      <h5 id="rsvp">You have joined this Workout</h5>
      <!-- link to google static map for location -->
        <%= link_to("map", event_path(event), id:"map") %>
        <hr></hr>
        
      <!-- replaces the "join button" to show the user that they ahve already joined this event -->
       

         <!-- if the previous statement is not true this hiiden from creates a button "join" to allow the cuurent user to join the event. When clicked it creates a line item on the event_user table -->
      <% else %>
            <%= form_for event.event_users.new do |f| %>
                    <%= f.hidden_field :event_id, value: event.id %>
                    <%= f.submit "Join", class: 'button' %><br> 
                
                   <!--  this is the counter.  it coutns the number of items in the event user table -->
                    <h5 id="rsvp">People RSVP'D:
                    </h5> 
                    <%= event.users.length %> 
                  <hr id="event_border"> 
            <% end %>
            <%= link_to("map", event_path(event)) %>

      <% end %>
      
  <% end %>
      <div class="event_buttons">
      <div class= "center"></div>
      <div id="new_event_button"><%= link_to("Add Workout", new_event_path) %></div><div></div>

      <!-- link to all the current users workouts -->
      <div id="my_event_button"><%= link_to("My Workouts", my_events_path) %></div><div></div>
      </div>
<% else %>
  <h4> Please sign in to join a workout </h4>
  <div>

    <!-- if neither previous statement is true this iteration displays an idex of events but only shows allowed information...not location or join button -->
  <% @events.each do |event| %>
      <strong>Workout:</strong> <%=event.event_name %>- <%=event.description %>, <%=event.difficulty %><br>
      <strong>Date:</strong> <%=event.date %><br>
      <strong>Time: </strong><%=event.time %>
      <p></p>
    </div>
     <hr id="event_border"> 
  <% end %>
<% end %>

<br>

<%= paginate @events.order(created_at: :desc) %>
</div>

app/views/events/my_events.html.erb
<!-- #this page shows all the individuals events that they have created or joined -->
<div class="banner">
<h2 id="header"><strong>My Workouts</strong></h2>
</div>

<div class="event_buttons">
     <div class= "center"></div>
  
      <div id="new_event_button"><%= link_to("Add Workout", new_event_path) %></div><div></div>

      <!-- link to all the current users workouts -->
      <div id="my_event_button"><%= link_to 'All Workouts', events_path %></div><div></div>
      </div>
<%= paginate @events.order(created_at: :desc) %>

<tbody>
  <!-- iterates throught he partial to show user all of their events and a static map -->
  <% @events.each do |event| %>
      
    <%= render partial: "event", locals:{event: event} %>
    <h5 id="rsvp">People RSVP'D for this workout:
     <%= event.users.length %></h5> 
    <%= link_to("map", "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{event.latitude}%2C#{event.longitude}") %>
       
   
    <hr></hr>
    
        
  <% end %>
  <div class="event_buttons">
     <div class= "center"></div>
  
      <div id="new_event_button"><%= link_to("Add Workout", new_event_path) %></div><div></div>

      <!-- link to all the current users workouts -->
      <div id="my_event_button"><%= link_to 'All Workouts', events_path %></div><div></div>
      </div>
  <%= paginate @events.order(created_at: :desc) %>

  
</tbody>

app/views/events/new.html.erb
<!-- this page iterates through and creates events via the form -->
<div class="wrapper">

  <h2 id="sign_in">Add Workout </h2>
  <div id= "sign_in_box">
    <%= form_for(@event) do |f| %>

      <div class="field">
        <%= f.label :Workout%><br>
        <%= f.text_field :event_name %>
      </div>
      <div class="field">
        <%= f.label :Description %><br>
        <%= f.text_area :description %>
      </div>
      <div class="field">
        <%= f.label :Date %>
        <%= f.text_field :date %>
        
        <%= f.label :Time %>
        <%= f.text_field :time %>
       
        <%= f.label :Address %>
        <%= f.text_field :address %>
        
        <%= f.label :Location %>
        <%= f.text_field :location %><br>
        
        <%= f.label :Difficulty %>
        <%= f.text_field :difficulty %><br>
      
      </div>
      <div class="actions">
        <%= f.submit "Create Workout", class: 'button_big'%>
      </div>
    <% end %>
  </div>
</div>
    <div class="wrapper">
    <!-- link to new event page -->
      <div class="event_buttons">
        <div class= "center"></div>
        
        <div id="new_event_button"><%= link_to("Add Workout", new_event_path) %></div>
        <div></div>

      <!-- link to all the current users workouts -->
      <div id="my_event_button"><%= link_to("My Workouts", my_events_path) %></div><div></div>
    </div>

app/views/events/show.html.erb
<div class="wrapper">
    <h1>New Workout</h1>

    <!-- displays the most recently created event and its map or which ever event map you are looking for with that event information -->
    <p>
      Name:<%= @event.event_name %>
      Description: <%= @event.description %><br>
        Date:<%= @event.date %>
        Time:<%= @event.time %>
        Address:<%= @event.address %><br>
        Location:<%= @event.location%><br>
      Difficulty:<%= @event.difficulty %><br>
      <%= link_to 'Edit', edit_event_path(@event) %> 
      <%= link_to 'All Workouts', events_path %><br>
      <%= image_tag("http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@event.latitude}%2C#{@event.longitude}") %>
      

    </p>


    <h2> All Your Workouts </h2> 
    
    <!-- iterates through all the current users event  -->
    <%  current_user.events.each do |event| %>
    <%= event.event_name  %>
    <%= event.description %><br>
    <%= event.date %>
    <%= event.time %>
    <%= event.address %>
    <%= event.location %><br>
    <%= event.difficulty %><br>
    
    <%= link_to("map", event_path(event)) %>
    <br>
    <% end %>

    <%= link_to 'All Workouts', events_path %>
  </div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>



<head>

  <title>CrankBuddy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='//fonts.googleapis.com/css?family=Droid+Serif:400,700|Oleo+Script|Reenie+Beanie:regular|Rock+Salt' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:300'rel='stylesheet' type='text/css'>
<!--   <link rel="stylesheet" type="text/css" href="assets/application.css">
 -->
</head>
 <!-- <div class="heading">
<h1 id="banner">FIT..Buddy! </h1>
<h5 id="tag_line">Find people to workout with, you decide what, when, and where!</h5>
</div> -->

<body>


<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<div class="nav_box">
  <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong id="email"><%= current_user.email %></strong><br>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>

<% end %>
</div>
<%= yield %>

</body>
</html>